#!/usr/bin/env python3
"""
diagnose_samples.py — Diagnose the root cause of abnormal Sample node counts generated by build_kg.py

Usage:
  python diagnose_samples.py --host 192.168.20.30 --database public --user xxx --password xxx
"""

import sys
import argparse
try:
    import pymysql
except ImportError:
    print("[ERROR] pymysql not installed. Run: pip install pymysql")
    sys.exit(1)


def diagnose(host, port, user, password, database):
    conn = pymysql.connect(
        host=host, port=port, user=user, password=password,
        database=database, charset='utf8mb4',
        cursorclass=pymysql.cursors.DictCursor
    )
    print(f"[OK] Connected to {host}:{port}/{database}\n")

    with conn.cursor() as cur:
        # ---- 1. Check all tables in the database ----
        print("=" * 60)
        print("1. Tables in the database")
        print("=" * 60)
        cur.execute("SHOW TABLES")
        all_tables = [row[list(row.keys())[0]] for row in cur.fetchall()]
        for t in all_tables:
            cur.execute(f"SELECT COUNT(*) as cnt FROM `{t}`")
            cnt = cur.fetchone()["cnt"]
            marker = " <<< target" if "public_general_2026" in t else ""
            print(f"  {t}: {cnt:,} rows{marker}")
        print()

        # ---- 2. public_general_2026 row count ----
        target_table = None
        for t in all_tables:
            if "public_general_2026" in t:
                target_table = t
                break

        if not target_table:
            print("[ERROR] public_general_2026 table not found!")
            print("  → Check whether FOCUS_TABLES config matches the actual table name")
            conn.close()
            return

        print("=" * 60)
        print(f"2. Detailed diagnosis of {target_table}")
        print("=" * 60)

        cur.execute(f"SELECT COUNT(*) as cnt FROM `{target_table}`")
        total_rows = cur.fetchone()["cnt"]
        print(f"  Total rows: {total_rows:,}")

        # ---- 3. sample_id distribution ----
        cur.execute(f"SELECT COUNT(DISTINCT sample_id) as cnt FROM `{target_table}`")
        distinct_ids = cur.fetchone()["cnt"]
        print(f"  Unique sample_id count: {distinct_ids:,}")

        cur.execute(f"SELECT COUNT(*) as cnt FROM `{target_table}` WHERE sample_id IS NULL")
        null_ids = cur.fetchone()["cnt"]
        if null_ids:
            print(f"  ⚠️  Rows with NULL sample_id: {null_ids}")

        cur.execute(f"SELECT COUNT(*) as cnt FROM `{target_table}` WHERE sample_id = ''")
        empty_ids = cur.fetchone()["cnt"]
        if empty_ids:
            print(f"  ⚠️  Rows with empty string sample_id: {empty_ids}")

        # ---- 4. Check deleted_at ----
        cur.execute(f"SELECT COUNT(*) as cnt FROM `{target_table}` WHERE deleted_at IS NOT NULL")
        deleted = cur.fetchone()["cnt"]
        if deleted:
            print(f"  ⚠️  Rows with non-NULL deleted_at: {deleted} (soft-delete flag)")

        print()

        # ---- 5. Simulate row → Sample node mapping ----
        print("=" * 60)
        print("3. Simulation of build_kg.py's _row_to_node_wide")
        print("=" * 60)

        # Read the first 5 rows and simulate the _row_to_node_wide logic
        cur.execute(f"SELECT * FROM `{target_table}` LIMIT 5")
        sample_rows = cur.fetchall()

        from scripts.build_kg import WIDE_TABLE_ENTITY_MAPPING
        extracted_cols = set(WIDE_TABLE_ENTITY_MAPPING.keys())
        extracted_cols.add("doi")
        extracted_cols.add("test")

        for i, row in enumerate(sample_rows):
            pk_val = row.get("sample_id", list(row.values())[0])
            node_id = f"smp_{pk_val}"
            col_count = len(row)
            kept_cols = sum(1 for c in row if c not in extracted_cols and row[c] is not None)
            print(f"  Row {i+1}: sample_id={pk_val} → node_id={node_id}")
            print(f"          {col_count} columns total, {kept_cols} kept as Sample properties "
                  f"({col_count - kept_cols} extracted as entities)")

        print()

        # ---- 6. Root cause analysis ----
        print("=" * 60)
        print("4. Root Cause Analysis")
        print("=" * 60)

        expected_sample_count = distinct_ids - (1 if null_ids or empty_ids else 0)

        if total_rows == distinct_ids and total_rows > 100:
            print(f"  ✅ Table has {total_rows:,} rows, each with a unique sample_id")
            print(f"  → build_kg.py should generate {total_rows:,} Sample nodes")
            print(f"  → If only 42 were generated, check build_kg.py's console output:")
            print(f"      '[INFO] Processing N rows from {target_table}' — what is the N value?")
            print(f"  → If N=42, MySQL returned 42 rows (data was filtered/truncated)")
            print(f"  → If N={total_rows}, there is a code bug (needs further investigation)")
        elif total_rows < 100:
            print(f"  ⚠️  Table only has {total_rows} rows of data")
            print(f"  → The database table may have been truncated, or connected to the wrong database")
            print(f"  → Previous build reports showed 17,055 Sample nodes")
        elif total_rows != distinct_ids:
            print(f"  ⚠️  Total rows ({total_rows:,}) ≠ unique sample_id count ({distinct_ids:,})")
            dup_count = total_rows - distinct_ids
            if dup_count > 0:
                print(f"  → {dup_count} rows have duplicate sample_ids, which will be overwritten in the KG")
                print(f"  → Final Sample node count = {distinct_ids:,}")

        print()

        # ---- 7. Last N sample_ids ----
        print("=" * 60)
        print("5. Latest sample_id samples")
        print("=" * 60)
        cur.execute(f"SELECT sample_id FROM `{target_table}` ORDER BY sample_id DESC LIMIT 10")
        for row in cur.fetchall():
            print(f"  {row['sample_id']}")

    conn.close()


def main():
    parser = argparse.ArgumentParser(
        description="Diagnose Sample node count issues in build_kg.py")
    parser.add_argument("--host", default="192.168.20.30")
    parser.add_argument("--port", type=int, default=33061)
    parser.add_argument("--user", default="wangchenglong")
    parser.add_argument("--password", default="")
    parser.add_argument("--database", default="public")
    args = parser.parse_args()

    diagnose(args.host, args.port, args.user, args.password, args.database)


if __name__ == "__main__":
    main()
